/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef log_CONSTANTS_H
#define log_CONSTANTS_H

#include "log_types.h"



class logConstants {
 public:
  logConstants();

};

extern const logConstants g_log_constants;



#endif
